### ISSUE TITLE
Error In Dout Gtkwave

### ISSUE THREAD

**Issue by Sohamraje137** [maomran/softmax#2]
I am getting the following output. Please let me know if there are any changes to be made in the code while running.

I get xxxxx on gtkwave on 698ns timescale

I ran

iverilog -o output2.vvp softmax.v adder.v divider.v exponential.v multiplier.v softmax_tb.v

vvp output2.vvp

gtkwave softmax_tb.vcd

![error_softmax](https://user-images.githubusercontent.com/31730816/83379002-1eab9680-a3f8-11ea-95c4-737d7c1d2c35.PNG)

**Comment by maomran** [comment]
There was an issue in the TB and I fixed it, please try it now.
